name: Build and Release ClaudeCage

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bubblewrap zip
          echo "Dependencies installed."

      # --- REVISED STEP: Deconstruct, Patch, and Reconstruct RunImage ---
      - name: Prepare Patched RunImage for Build
        run: |
          echo "Downloading RunImage..."
          curl -# -Lo runimage https://github.com/VHSgunzo/runimage/releases/download/continuous/runimage-x86_64
          chmod +x runimage

          echo "Deconstructing the original RunImage..."
          OFFSET=$(./runimage --runtime-offset)
          dd if=runimage of=runtime bs=1 count=$(($OFFSET - 1))
          dd if=runimage of=fs_and_config.img bs=1 skip=$(($OFFSET - 1))
          
          echo "Determining filesystem type and ensuring it is SquashFS..."
          # Create a directory to unpack into.
          mkdir ./rootfs_unpacked
          # We now ONLY use unsquashfs. We test if the image is SquashFS first.
          if ./runimage --runtime-unsquashfs -s fs_and_config.img &>/dev/null; then
              echo "Filesystem is SquashFS. Proceeding to unpack."
              ./runimage --runtime-unsquashfs -f -d ./rootfs_unpacked fs_and_config.img
          else
              echo "Filesystem is DwarFS. Converting to SquashFS first..."
              mkdir ./temp_dwarfs_unpacked
              # Unpack the DwarFS image
              ./runimage --runtime-dwarfsextract -i fs_and_config.img -o ./temp_dwarfs_unpacked
              # Repack it as a SquashFS image
              ./runimage --runtime-mksquashfs ./temp_dwarfs_unpacked fs_and_config.img -no-xattrs -noappend
              # Now unpack the new SquashFS image
              ./runimage --runtime-unsquashfs -f -d ./rootfs_unpacked fs_and_config.img
              rm -rf ./temp_dwarfs_unpacked
          fi
          
          echo "Verifying extraction. Listing contents of ./rootfs_unpacked/var/RunDir/:"
          # This diagnostic will prove the files exist before we try to patch them.
          ls -lR ./rootfs_unpacked/var/RunDir/

          PATCH_TARGET_FILE="./rootfs_unpacked/var/RunDir/Run.sh"
          if [ ! -f "$PATCH_TARGET_FILE" ]; then
              echo "FATAL: Could not find Run.sh at the expected path: $PATCH_TARGET_FILE"
              exit 1
          fi

          echo "Patching $PATCH_TARGET_FILE..."
          sed -i 's|if \[ -f /sys/module/apparmor/parameters/restrict_unprivileged_userns \]; then|# &|' "$PATCH_TARGET_FILE"
          
          echo "Re-packing the patched rootfs as SquashFS..."
          ./runimage --runtime-mksquashfs ./rootfs_unpacked fs_patched.img -no-xattrs -noappend

          echo "Re-assembling the patched RunImage..."
          grep -a --binary-files=text -o '{.*}$' fs_and_config.img > config.json
          cat runtime fs_patched.img config.json > runimage_patched
          chmod +x runimage_patched

          echo "Patched RunImage created successfully."

      - name: Run Build Script
        run: |
          echo "Running build.sh using the patched executable and SUID bwrap..."
          chmod +x ./build.sh
          env \
            RIM_SYS_BWRAP=1 \
            ./runimage_patched ./build.sh
          echo "build.sh completed."

      - name: Verify output files exist
        run: |
          echo "Verifying output files..."
          ls -l ClaudeCage ClaudeCage.rcfg
          test -f ClaudeCage
          test -f ClaudeCage.rcfg
          echo "Output files verified."

      - name: Create release archive
        run: |
          echo "Creating ClaudeCage_release.zip..."
          zip ClaudeCage_release.zip ClaudeCage ClaudeCage.rcfg
          echo "ClaudeCage_release.zip created."

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.sha_short }}
          name: Automated Build ${{ github.run_id }} (Commit ${{ github.sha_short }})
          body: |
            This is an automated build from commit `${{ github.sha_short }}` on branch `${{ github.ref_name }}`.
            [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            The attached `ClaudeCage_release.zip` contains the `ClaudeCage` executable and `ClaudeCage.rcfg` configuration file.
          files: ClaudeCage_release.zip
