name: Build and Release ClaudeCage

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build_and_release:
    runs-on: ubuntu-latest # Specify the runner environment (Ubuntu Linux)
    permissions:
      contents: write # Grant permission to write to repository contents (for creating release)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your repository code

      # --- NEW STEP: Install SUID Bubblewrap ---
      # This step uses sudo to install the system's bubblewrap. The package manager
      # will set it up with SUID permissions, which acts as a fallback when
      # unprivileged user namespaces are disabled by AppArmor.
      - name: Install SUID Bubblewrap
        run: |
          sudo apt-get update
          sudo apt-get install -y bubblewrap
          echo "bubblewrap installed."

      # --- MODIFIED STEP: Run build.sh with the correct environment variable ---
      - name: Make build.sh executable and run it
        # We set RIM_SYS_BWRAP=1 to tell RunImage to use the SUID bubblewrap
        # we just installed, bypassing the AppArmor restriction.
        run: |
          echo "Running build.sh..."
          chmod +x ./build.sh
          env RIM_SYS_BWRAP=1 ./build.sh
          echo "build.sh completed."

      - name: Verify output files exist
        run: |
          echo "Verifying output files..."
          ls -l ClaudeCage ClaudeCage.rcfg
          test -f ClaudeCage
          test -f ClaudeCage.rcfg
          echo "Output files verified."

      - name: Create release archive
        run: |
          echo "Creating ClaudeCage_release.zip..."
          zip ClaudeCage_release.zip ClaudeCage ClaudeCage.rcfg
          echo "ClaudeCage_release.zip created."

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.sha_short }}
          name: Automated Build ${{ github.run_id }} (Commit ${{ github.sha_short }})
          body: |
            This is an automated build from commit `${{ github.sha_short }}` on branch `${{ github.ref_name }}`.

            [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            The attached `ClaudeCage_release.zip` contains the `ClaudeCage` executable and `ClaudeCage.rcfg` configuration file.
          files: ClaudeCage_release.zip
