name: Build and Release

on:
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y zip
          echo "Dependencies installed."

      - name: Configure Runner Environment for RunImage
        run: |
          echo "Disabling AppArmor restriction on unprivileged user namespaces..."
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          echo "Environment configured."

      - name: Run Build Script
        run: |
          echo "Running build.sh in the correctly configured environment..."
          chmod +x ./build.sh
          ./build.sh
          echo "build.sh completed."

      - name: Verify output files exist
        run: |
          echo "Verifying output files..."
          ls -l ClaudeCage ClaudeCage.rcfg
          test -f ClaudeCage
          test -f ClaudeCage.rcfg
          echo "Output files verified."

      - name: Create release archive
        run: |
          echo "Creating ClaudeCage-linux-x86_64.zip..."
          zip ClaudeCage-linux-x86_64.zip ClaudeCage ClaudeCage.rcfg
          echo "ClaudeCage-linux-x86_64.zip created."
      
      - name: Generate Release Tag
        run: echo "TAG_NAME=build-$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          body: |
            This is an automated build from commit `${{ github.sha }}` on branch `${{ github.ref_name }}`.

            [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            The attached `ClaudeCage-linux-x86_64.zip` contains the `ClaudeCage` executable and `ClaudeCage.rcfg` configuration file.
          files: ClaudeCage-linux-x86_64.zip
