name: Build and Release ClaudeCage

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bubblewrap zip
          echo "Dependencies installed."

      # --- REVISED STEP: Deconstruct, Patch, and Reconstruct RunImage ---
      - name: Prepare Patched RunImage for Build
        run: |
          echo "Downloading RunImage..."
          curl -# -Lo runimage https://github.com/VHSgunzo/runimage/releases/download/continuous/runimage-x86_64
          chmod +x runimage

          echo "Deconstructing the original RunImage..."
          OFFSET=$(./runimage --runtime-offset)
          dd if=runimage of=runtime bs=1 count=$(($OFFSET - 1))
          dd if=runimage of=fs_and_config.img bs=1 skip=$(($OFFSET - 1))

          echo "Unpacking the rootfs..."
          mkdir ./rootfs_parent
          # The extraction tools create their own subdirectory, so we run them inside a parent dir.
          (
            cd ./rootfs_parent
            # Try DwarFS first
            if ../runimage --runtime-dwarfsextract -i ../fs_and_config.img; then
                FS_TYPE="dwfs"
                # The tool creates a 'rootfs' directory.
                EXTRACTED_DIR="rootfs"
            else
                echo "DwarFS extract failed, trying SquashFS..."
                # The runimage unsquashfs extracts to a 'squashfs-root' dir by default.
                ../runimage --runtime-unsquashfs -d squashfs-root ../fs_and_config.img
                FS_TYPE="sqfs"
                EXTRACTED_DIR="squashfs-root"
            fi
            # We add a marker file to communicate the directory name back to the parent shell.
            echo "$EXTRACTED_DIR" > .extraction_dir_name
          )
          
          # Read the name of the directory created by the extractor
          EXTRACTED_SUBDIR_NAME=$(cat ./rootfs_parent/.extraction_dir_name)
          EXTRACTED_ROOT_PATH="./rootfs_parent/$EXTRACTED_SUBDIR_NAME"
          
          echo "Verifying extraction at $EXTRACTED_ROOT_PATH..."
          # Add a diagnostic listing to be absolutely sure
          ls -l "$EXTRACTED_ROOT_PATH/var/RunDir"

          PATCH_TARGET_FILE="$EXTRACTED_ROOT_PATH/var/RunDir/Run.sh"
          if [ ! -f "$PATCH_TARGET_FILE" ]; then
              echo "FATAL: Could not find Run.sh at the expected path: $PATCH_TARGET_FILE"
              exit 1
          fi

          echo "Patching $PATCH_TARGET_FILE..."
          sed -i 's|if \[ -f /sys/module/apparmor/parameters/restrict_unprivileged_userns \]; then|# &|' "$PATCH_TARGET_FILE"
          
          echo "Re-packing the patched rootfs from $EXTRACTED_ROOT_PATH..."
          if [ "$FS_TYPE" = "dwfs" ]; then
              ./runimage --runtime-mkdwarfs -i "$EXTRACTED_ROOT_PATH" -o fs_patched.img
          else
              ./runimage --runtime-mksquashfs "$EXTRACTED_ROOT_PATH" fs_patched.img -no-xattrs -noappend
          fi

          echo "Re-assembling the patched RunImage..."
          grep -a --binary-files=text -o '{.*}$' fs_and_config.img > config.json
          cat runtime fs_patched.img config.json > runimage_patched
          chmod +x runimage_patched

          echo "Patched RunImage created successfully."

      - name: Run Build Script
        run: |
          echo "Running build.sh using the patched executable and SUID bwrap..."
          chmod +x ./build.sh
          env \
            RIM_SYS_BWRAP=1 \
            ./runimage_patched ./build.sh
          echo "build.sh completed."

      - name: Verify output files exist
        run: |
          echo "Verifying output files..."
          ls -l ClaudeCage ClaudeCage.rcfg
          test -f ClaudeCage
          test -f ClaudeCage.rcfg
          echo "Output files verified."

      - name: Create release archive
        run: |
          echo "Creating ClaudeCage_release.zip..."
          zip ClaudeCage_release.zip ClaudeCage ClaudeCage.rcfg
          echo "ClaudeCage_release.zip created."

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.sha_short }}
          name: Automated Build ${{ github.run_id }} (Commit ${{ github.sha_short }})
          body: |
            This is an automated build from commit `${{ github.sha_short }}` on branch `${{ github.ref_name }}`.
            [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            The attached `ClaudeCage_release.zip` contains the `ClaudeCage` executable and `ClaudeCage.rcfg` configuration file.
          files: ClaudeCage_release.zip
